# Generated by Django 3.2.6 on 2021-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Notes_of_Interest',
            field=models.TextField(null=True),
        ),
    ]
