# Generated by Django 3.2.5 on 2021-08-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Code',
            new_name='Password',
        ),
    ]
