# Generated by Django 3.2.6 on 2021-08-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_notes_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone_Number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Professional_Experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Surname',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
