# Generated by Django 3.2.6 on 2021-09-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address', models.EmailField(max_length=240, unique=True)),
                ('Professional_Experience', models.TextField(null=True)),
                ('Education', models.TextField(null=True)),
                ('Skills', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Notes_of_Interest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Professional_Experience',
        ),
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
