# Generated by Django 3.2.6 on 2021-09-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210904_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='PrivateEducation',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='PrivateProf_Experience',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='PrivateSkills',
            field=models.BooleanField(default='False'),
        ),
    ]
