# Generated by Django 3.2.6 on 2021-09-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210904_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='PrivateEducation',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='PrivateProf_Experience',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='PrivateSkills',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
