# Generated by Django 3.2.6 on 2021-09-08 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210904_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address', models.EmailField(max_length=240, unique=True)),
                ('NameAD', models.CharField(max_length=240, null=True)),
                ('TextAD', models.TextField(null=True)),
                ('ApplicationUsers', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=240), size=None), size=None)),
            ],
        ),
    ]
