# Generated by Django 3.2.6 on 2021-09-14 01:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address_sender', models.EmailField(max_length=240)),
                ('Email_Address_receiver', models.EmailField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address', models.EmailField(max_length=240, unique=True)),
                ('Friend_List', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=240), size=None), size=None)),
            ],
        ),
    ]
