# Generated by Django 3.2.6 on 2021-09-14 02:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_connection_request_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address_One', models.EmailField(max_length=240)),
                ('Email_Address_Two', models.EmailField(max_length=240)),
                ('ID', models.IntegerField()),
                ('Content', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
            ],
        ),
    ]
