# Generated by Django 3.2.6 on 2021-09-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_conversation_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address', models.EmailField(max_length=240, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Connection_request',
        ),
        migrations.DeleteModel(
            name='Conversation_List',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='ApplicationUsers',
        ),
        migrations.AddField(
            model_name='ad',
            name='ApplicationUsers',
            field=models.ManyToManyField(blank=True, to='User.PersonAD'),
        ),
    ]
