# Generated by Django 3.2.6 on 2021-09-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20210916_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='Email_Address',
            field=models.EmailField(max_length=240),
        ),
    ]
