# Generated by Django 3.2.6 on 2021-09-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_ad_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address_Sender', models.EmailField(max_length=240)),
                ('Email_Address_Receiver', models.EmailField(max_length=240)),
            ],
        ),
    ]
