# Generated by Django 3.2.6 on 2021-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_article_commentarticle_personarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Current_date',
            field=models.DateTimeField(null=True),
        ),
    ]
