# Generated by Django 3.2.6 on 2021-09-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_article_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Current_date',
            field=models.TextField(null=True),
        ),
    ]
