# Generated by Django 3.2.6 on 2021-09-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_article_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='NameArticle',
            field=models.TextField(null=True),
        ),
    ]
