# Generated by Django 3.2.6 on 2021-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_article_namearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address', models.EmailField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Friend_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address', models.EmailField(max_length=240, unique=True)),
                ('Friend_List', models.ManyToManyField(to='User.Friend_List')),
            ],
        ),
    ]
