# Generated by Django 3.2.6 on 2021-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_alter_friend_status_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_status',
            name='Friend_List',
            field=models.TextField(null=True),
        ),
    ]
