# Generated by Django 3.2.6 on 2021-09-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_auto_20210921_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ApplicationUsers',
        ),
        migrations.AddField(
            model_name='ad',
            name='ApplicationUsers',
            field=models.TextField(null=True),
        ),
    ]
