# Generated by Django 3.2.6 on 2021-09-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_auto_20210921_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonAD',
        ),
    ]
