# Generated by Django 3.2.6 on 2021-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_article_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Address1', models.EmailField(max_length=240)),
                ('Email_Address2', models.EmailField(max_length=240)),
                ('Content', models.TextField(max_length=240)),
                ('ID', models.CharField(max_length=5)),
            ],
        ),
    ]
