# Generated by Django 3.2.6 on 2021-09-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='ID',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
