# Generated by Django 3.2.6 on 2021-09-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_alter_discussion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='ID',
            new_name='Content_Discussion',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='Content',
            new_name='Εmail_Field',
        ),
    ]
