# Generated by Django 3.2.6 on 2021-09-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_auto_20210925_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='Content_Discussion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='Εmail_Field',
            field=models.TextField(null=True),
        ),
    ]
